package ch.heigvd.api.labio.impl.transformers;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 *       *** IMPORTANT WARNING : DO NOT EDIT THIS FILE ***
 *
 * This file is used to specify what you have to implement. To check your work,
 * we will run our own copy of the automated tests. If you change this file,
 * then you will introduce a change of specification!!!
 *
 * @author Juergen Ehrensberger
 */
public class LineNumberingCharTransformerTest {

    private String transform(String input) {
        LineNumberingCharTransformer transformer = new LineNumberingCharTransformer();
        StringBuilder output = new StringBuilder();
        for (int i=0; i<input.length(); i++) {
            String s = Character.toString(input.charAt(i));
            output.append(transformer.transform(s));
        }
        return output.toString();
    }

    @Test
    public void itShouldAddANumberToStringWithOneLine() {
        String source = "This is one line";
        String target = "1. This is one line";
        assertEquals(target, transform(source));
    }

    @Test
    public void itShouldAddNumbersToStringWithTwoLines() {
        String source = "This is one line\nAnd a second line.";
        String target = "1. This is one line\n2. And a second line.";
        assertEquals(target, transform(source));
    }

    @Test
    public void itShouldAddANumberForAnEmptyLine() {
        String source = "\n";
        String target = "1. \n2. ";
        assertEquals(target, transform(source));
    }

    @Test
    public void itShouldRemoveCarriageReturn() {
        String source = "This is a line.\r\n";
        String target = "1. This is a line.\n2. ";
        assertEquals(target, transform(source));
    }

    @Test
    public void itShouldWorkWithUnicodeCharacters() {
        String source = "ABCD ÄÖÜ ÀÉÙÇ 北京 ☺";
        String target = "1. ABCD ÄÖÜ ÀÉÙÇ 北京 ☺";
        assertEquals(target, transform(source));
    }
}
